name: test
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install
      - run: npm run build
      - run: mkdir -p build

      - name: Create idoc config
        run: |
          cat > idoc.yml << EOF
          site: "Folder Tree {{version}}"
          menus:
            Home: index.html
            Sponsor: https://jaywcjlove.github.io/#/sponsor
          footer: |
            <a href="https://jaywcjlove.github.io/#/sponsor" target="_blank">Sponsor</a> • 
            <a href="https://jaywcjlove.github.io/changelog-generator" target="_blank">Changelog Generator</a> • 
            <a href="https://jaywcjlove.github.io/create-tag-action" target="_blank">Create Tag</a> • 
            <a href="https://jaywcjlove.github.io/github-action-contributors" target="_blank">Contributors</a> • 
            <a href="https://jaywcjlove.github.io/generated-badges" target="_blank">Generated Badges</a>
            <br />
            Released under the MIT License. Copyright © {{idocYear}} Kenny Wong<br />
            Generated by <a href="https://github.com/jaywcjlove/idoc" target="_blank">idoc</a> v{{idocVersion}}
          
          EOF

      - run: npm install idoc@1 -g
      - run: idoc
      - name: gh-pages README.md
        working-directory: dist
        run: |
          cat > README.md << EOF
          Website: https://jaywcjlove.github.io/github-action-folder-tree  
          EOF

      - name: Is a tag/release created auto? 
        id: create_tag
        uses: jaywcjlove/create-tag-action@main
        with:
          # test: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'
          package-path: ./package.json

      - name: get tag version
        id: tag_version
        uses: jaywcjlove/changelog-generator@main

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          commit_message: ${{steps.tag_version.outputs.tag}} ${{ github.event.head_commit.message }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

      - name: Generate Changelog
        id: changelog
        uses: jaywcjlove/changelog-generator@main
        with:
          head-ref: ${{steps.create_tag.outputs.version}}
          filter: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'

      - name: Create Release
        uses: jaywcjlove/create-tag-action@main
        with:
          # test: '[R|r]elease[d]\s+[v|V]\d(\.\d+){0,2}'
          package-path: ./package.json
          release: true
          body: |
            [![Buy me a coffee](https://img.shields.io/badge/Buy%20me%20a%20coffee-048754?logo=buymeacoffee)](https://jaywcjlove.github.io/#/sponsor)
            Documentation ${{ steps.changelog.outputs.tag }}: https://raw.githack.com/jaywcjlove/github-action-upload-assets/${{ steps.changelog.outputs.gh-pages-short-hash }}/index.html  
            Comparing Changes: ${{ steps.changelog.outputs.compareurl }} 

            ${{ steps.changelog.outputs.changelog }}

            ```yml
            - name: Release Upload Assets
              uses: jaywcjlove/github-action-upload-assets@main
              with:
                asset-path: test.*
            ```

      - run: echo "Hello World" > test.txt
      - name: Compress test Example.
        run: zip -r -y test.zip test.txt -x "node_modules/*"

      - run: echo "version - ${{ steps.create_tag.outputs.version }}"

      - name: Release Upload Assets
        # uses: jaywcjlove/github-action-upload-assets@main
        # if: steps.create_tag.outputs.successful == 'true'
        continue-on-error: true
        uses: ./
        with:
          tag: ${{ steps.create_tag.outputs.version }}
          asset-path: test.*
        
      - run: echo "Hello World" > tag.txt
      - name: Release Upload Assets
        # uses: jaywcjlove/github-action-upload-assets@main
        continue-on-error: true
        uses: ./
        with:
          tag: v0.0.3
          asset-path: tag.*
    

